services:
  lucky_wallet:
    container_name: lucky_wallet
    image: lucky_wallet
    restart: always
    build: .
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
